### ISSUE TITLE
如果有个词云图就完美了

### ISSUE THREAD

**Issue by John-githu** [ahnuchen/weixin-group-annual-report#1]
如果有个词云图就完美了，期待，期待！

**Comment by ahnuchen** [comment]
> 如果有个词云图就完美了，期待，期待！

可以加

**Comment by ahnuchen** [comment]
> 如果有个词云图就完美了，期待，期待！

功能已经有了哦，还有发言时间段分布图表，见效果图

**Comment by tyl511** [comment]
你好，请问我按照步骤输入导出的群聊记录目录后，为什么总是显示输入目录不正确

![f30995bfd375d0d065e231eddd9fb2a](https://github.com/ahnuchen/weixin-group-annual-report/assets/118172888/7a7e6924-45b6-4db1-8534-386e9db42c45)

**Comment by tyl511** [comment]
> > 如果有个词云图就完美了，期待，期待！
> 
> 功能已经有了哦，还有发言时间段分布图表，见效果图

你好作者，可以请教一下这个问题吗，万分感谢

**Comment by ahnuchen** [comment]
> > > 如果有个词云图就完美了，期待，期待！
> > 
> > 
> > 功能已经有了哦，还有发言时间段分布图表，见效果图
> 
> 你好作者，可以请教一下这个问题吗，万分感谢

仔细看使用说明，用留痕导出html格式聊天记录，目录下肯定有个index.html，

**Comment by tyl511** [comment]
> > > > 如果有个词云图就完美了，期待，期待！
> > > 
> > > 
> > > 功能已经有了哦，还有发言时间段分布图表，见效果图
> > 
> > 
> > 你好作者，可以请教一下这个问题吗，万分感谢
> 
> 仔细看使用说明，用留痕导出html格式聊天记录，目录下肯定有个index.html，

作者你好，我认真查看了一下导出的聊天数据，只找到一个   {群聊名}.html    文件    我仔细检查了输入的目录，还望作者能够再看一下问题所在。         我对这方面不是很熟悉

如果打扰到作者，非常抱歉！

![f30995bfd375d0d065e231eddd9fb2a](https://github.com/ahnuchen/weixin-group-annual-report/assets/118172888/5839f38f-86ee-442e-95bb-bc2f8bd1eb50)

![f30995bfd375d0d065e231eddd9fb2a](https://github.com/ahnuchen/weixin-group-annual-report/assets/118172888/6bf83839-d9ab-459a-a8ce-a08b0284af13)

**Comment by tyl511** [comment]
> > > > 如果有个词云图就完美了，期待，期待！
> > > 
> > > 
> > > 功能已经有了哦，还有发言时间段分布图表，见效果图
> > 
> > 
> > 你好作者，可以请教一下这个问题吗，万分感谢
> 
> 仔细看使用说明，用留痕导出html格式聊天记录，目录下肯定有个index.html，

感谢，解决了，我把导出的html放到项目同名目录下，并改成和上一级目录同名。
