### ISSUE TITLE
nodejieba2.6.0已被删除，有没有可以替代的方案

### ISSUE THREAD

**Issue by ravio767** [ahnuchen/weixin-group-annual-report#2]
如题

**Comment by ahnuchen** [comment]
https://www.npmjs.com/package/@node-rs/jieba

可以试一下

**Comment by ahnuchen** [comment]
刚看了一下啊，node版本太高了不行，不大于v16就行

**Comment by ravio767** [comment]
已解决，node用的20版本，npm install https://github.com/yanyiwu/nodejieba.git后在该目录下npm install后将(https://github.com/yanyiwu/nodejieba/releases/download/v2.5.2/nodejieba-v2.5.2-node-v88-win32-x64.tar.gz)解压到build release目录下

**Comment by Bromaomao** [comment]
> https://www.npmjs.com/package/@node-rs/jieba
> 
> 可以试一下

这个装了以后

> https://www.npmjs.com/package/@node-rs/jieba
> 
> 可以试一下

这个装了以后输入npm run prepare还是显示no module named "nodejieba"

**Comment by Bromaomao** [comment]
> https://www.npmjs.com/package/@node-rs/jieba
> 
> 可以试一下

这个装了以后输入npm run prepare还是显示no module named "nodejieba"

**Comment by ahnuchen** [comment]
> > https://www.npmjs.com/package/@node-rs/jieba
> > 可以试一下
> 
> 这个装了以后输入npm run prepare还是显示no module named "nodejieba"

不好意思啊，用rs-jieba需要自己改代码。试着node降级到v16或者v14吧

**Comment by ahnuchen** [comment]
尝试用nodev16
