### ISSUE TITLE
node_modules vite包报错

### ISSUE THREAD

**Issue by Starssgo** [ahnuchen/weixin-group-annual-report#3]
你好，请问你的node版本是多少，我使用v15.9.0，在npm run dev出现如下报错

![image](https://github.com/ahnuchen/weixin-group-annual-report/assets/50407469/1fad8f39-551c-4cca-8a20-916799ccd8ab)

**Comment by Starssgo** [comment]
更新v16.0.0解决

**Comment by tyl511** [comment]
你好，请问你成功运行了吗？
请问我导出后输入聊天记录目录提示输入错误，有什么需要注意的问题吗

**Comment by tyl511** [comment]
> 更新v16.0.0解决

你好，请问输入聊天记录目录有什么要注意的吗，一直提示我输入路径不正确，万分感谢！！
